name: skript-advancements
version: '${project.version}'
main: me.hotpocket.skriptadvancements.SkriptAdvancements
api-version: 1.16
depend: [ Skript ]
authors: [ hotpocket184 ]
description: Allows you to manipulate advancements in Skript.
